#!/bin/bash
# Make this script exit at the first non-zero exit code. Fast-fail.
set -e

name="phpMyAdmin"
url="http://sourceforge.net/projects/phpmyadmin/files/latest/download?source=files"
# Version 4.0.0 seems to be a zip file rather than tar.bz2
outfile="phpmyadmin.latest.zip"

install_dir=~/data/installedPhpMyAdmin

msg() {
    echo "$name: $*."
}

# Emulate tar's --strip-components=1
# from http://superuser.com/questions/518347/equivalent-to-tars-strip-components-1-in-unzip
unzipstrip() {
    local zip=$1
    local dest=${2:-.}
    local temp=$(mktemp -d)
    unzip -d "$temp" "$zip"
    mkdir -p "$dest"
    shopt -s dotglob
    local f=("$temp"/*)
    if (( ${#f[@]} == 1 )) && [[ -d "${f[0]}" ]] ; then
        mv "$temp"/*/* "$dest"
    else
        mv "$temp"/* "$dest"
    fi && rmdir "$temp"/* "$temp"
}

install_pma() {
    if [ ! -d $install_dir ] ; then
        msg "downloading and installing the latest version"

        [ -d $install_dir ] || mkdir -p $install_dir
        curl -sSL --retry 3 -o $outfile $url 
	
	msg "Download successful. Unpacking."
	unzipstrip $outfile $install_dir
	# Swap this for unzip if phpMyAdmin goes back to tar.bz2
	# tar --strip-components=1 -xf $outfile -C $install_dir

    else
        msg "phpMyAdmin already installed"
    fi
}

configure_pma() {
    if [ ! -f $install_dir/config.inc.php ] ; then
        msg "installing configuration files"

        rm -rf $install_dir/config

        secret=`dd if=/dev/urandom of=/dev/stdout bs=32 count=1 2>/dev/null \
                | shasum | cut '-d ' -f 1`
        sed -i ~/current/config.inc.php.in -e "s/@BLOWFISH_SECRET@/$secret/"
        install -m 440 ~/current/config.inc.php.in $install_dir/config.inc.php

        cp ~/current/nginx.conf ~/current/robots.txt $install_dir/
    else
        msg "already configured"
    fi
}

pivot_current() {
    msg "rewriting ~/current to point to the install directory"

    ln -snf $install_dir ~/current
}

install_pma
configure_pma
pivot_current

exit 0
